create table author (
    type varchar(6) not null,
    id bigint generated by default as identity,
    nick_name varchar(30),
    birth_date DATE not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    version bigint not null,
    literary_genre varchar(255),
    primary key (id)
);

create table book (
    id bigint generated by default as identity,
    title varchar(50) not null,
    version bigint not null,
    primary key (id)
);

create table book_author (
    book_id bigint not null,
    author_id bigint not null,
    primary key (book_id, author_id)
);

create table book_exemplar (
    id bigint generated by default as identity,
    serial_number varchar(15) not null,
    book_cover varchar(255) not null,
    pages_count integer not null,
    paper_size varchar(255) not null,
    book_fk bigint not null,
    primary key (id)
);

alter table book_exemplar
    add constraint UK_book_serial_number  unique (serial_number);

alter table book_author
    add constraint FK_book_author_author_id
    foreign key (author_id)
    references author;

alter table book_author
    add constraint FK_book_author_book_id
    foreign key (book_id)
    references book;

alter table book_exemplar
    add constraint FK_book_exemplar_book_id
    foreign key (book_fk)
    references book;
